STATE_SIZE = 148

MEMORY_MAX_LENGTH = 2000

GAMMA = 0.95

INITIAL_EPSILON = 1.0
EPSILON_DECAY = 0.995
MINIMUM_EPSILON = 0.01

LEARNING_RATE = 0.001

SHOULD_TRACK_ORDER_COUNT = 4

PASSING_TABLE_X = 9

ACTION_CUT_A = 'cut a'
ACTION_CUT_B = 'cut b'
ACTION_MIX_A_AND_C = 'mix a and c'
ACTION_PASS_C = 'pass c'
ACTION_PASS_MIXED_BOWL = 'pass mixed bowl'
ACTION_PASS_DIRTY_PLATE = 'pass dirty plate'
ACTION_PASS_CLEAN_PLATE = 'pass clean plate'
ACTION_COOK_B = 'cook b'
ACTION_COOK_MIXED_BOWL = 'cook mixed bowl'
ACTION_PLATE_A = 'plate a'
ACTION_PLATE_B = 'plate b'
ACTION_SUBMIT_A = 'submit a'
ACTION_SUBMIT_B = 'submit b'
ACTION_WASH_PLATE = 'wash plate'
ACTION_PUT_ASIDE_C = 'put aside c'
ACTION_PUT_ASIDE_MIXED_BOWL = 'put aside mixed bowl'
ACTION_PUT_ASIDE_DIRTY_PLATE = 'put aside dirty plate'
ACTION_PUT_ASIDE_CLEAN_PLATE = 'put aside clean plate'
ACTION_PUT_ASIDE_COOKABLE_CONTAINER = 'put aside cookable container'
ACTION_DO_NOTHING = ''

SIDE_LEFT = 'left'
SIDE_RIGHT = 'right'

LEFT_SIDE_ACTION_CHOICES = [
    ACTION_CUT_A,
    ACTION_MIX_A_AND_C,
    ACTION_PASS_MIXED_BOWL,
    ACTION_PASS_CLEAN_PLATE,
    ACTION_WASH_PLATE,
    ACTION_PUT_ASIDE_C,
    ACTION_PUT_ASIDE_MIXED_BOWL,
    ACTION_PUT_ASIDE_DIRTY_PLATE,
    ACTION_DO_NOTHING
]

RIGHT_SIDE_ACTION_CHOICES = [
    ACTION_CUT_B,
    ACTION_PASS_C,
    ACTION_PASS_DIRTY_PLATE,
    ACTION_COOK_B,
    ACTION_COOK_MIXED_BOWL,
    ACTION_PLATE_A,
    ACTION_PLATE_B,
    ACTION_SUBMIT_A,
    ACTION_SUBMIT_B,
    ACTION_PUT_ASIDE_MIXED_BOWL,
    ACTION_PUT_ASIDE_CLEAN_PLATE,
    ACTION_DO_NOTHING
]

ALL_ACTION_CHOICES = LEFT_SIDE_ACTION_CHOICES + RIGHT_SIDE_ACTION_CHOICES