DIRECTION_UP = 0
DIRECTION_LEFT = 1
DIRECTION_RIGHT = 2
DIRECTION_DOWN = 3

WASH_TICKS = 4
MIX_TICKS = 8
COOK_TICKS = 8
CUT_TICKS = 4

PROCESS_CUT = 'cut'
PROCESS_MIXED = 'mixed'
PROCESS_COOKED = 'cooked'