
DIRECTION_UPPER_LEFT = 'upper_left'
DIRECTION_UP = 'up'
DIRECTION_UPPER_RIGHT = 'upper_right'
DIRECTION_LEFT = 'left'
DIRECTION_RIGHT = 'right'
DIRECTION_LOWER_LEFT = 'lower_left'
DIRECTION_DOWN = 'down'
DIRECTION_LOWER_RIGHT = 'lower_right'

WASH_TICKS = 8
MIX_TICKS = 16
OVERMIX_TICKS = 24
COOK_TICKS = 16
OVERCOOK_TICKS = 24
CUT_TICKS = 8

PROCESS_CUT = 'cut'
PROCESS_MIXED = 'mixed'
PROCESS_COOKED = 'cooked'

ACTION_WALK = 'walk'
ACTION_DASH = 'dash'
ACTION_USE = 'use'
ACTION_PICK = 'pick'
ACTION_PUT = 'put'

WALK_DISTANCE = 1
DASH_DISTANCE = 3

PLATE_RESPAWN_TIME = 16

INGREDIENT_A_NAME = 'a'
INGREDIENT_B_NAME = 'b'
INGREDIENT_C_NAME = 'c'

TIME_GIVEN = 2800