DIRECTION_UP = 'up'
DIRECTION_LEFT = 'left'
DIRECTION_RIGHT = 'right'
DIRECTION_DOWN = 'down'

WASH_TICKS = 4
MIX_TICKS = 8
COOK_TICKS = 8
CUT_TICKS = 4

PROCESS_CUT = 'cut'
PROCESS_MIXED = 'mixed'
PROCESS_COOKED = 'cooked'

ACTION_WALK = 'walk'
ACTION_DASH = 'dash'
ACTION_USE = 'use'
ACTION_PICK = 'pick'
ACTION_PUT = 'put'

WALK_DISTANCE = 1
DASH_DISTANCE = 3

PENALTY = 100
PLATE_RESPAWN_TIME = 10